### PR TITLE
Bug/200

### LINKED ISSUE #200: alt text missing on author/article teaser images

### PR DESCRIPTION
**Pull request by kailasnadh790**
Fix #200 
Test URLs:
- After: https://bug-200--famous-smoke-cigaradvisor--hlxsites.hlx.page/cigaradvisor
- After: https://bug-200--famous-smoke-cigaradvisor--hlxsites.hlx.page/cigaradvisor/category/industry-news/cigar-news-cao-flathead-resonator-is-lines-biggest-vitola

### CODE REVIEW

File: cigaradvisor/blocks/article-teaser/article-teaser.js [hunk 1]
```diff
@@ -30,6 +30,7 @@ export function buildArticleTeaser(parentElement, article) {
   };
 
   const picture = createOptimizedPicture(article.image);
+  picture.querySelector('img').setAttribute('alt', article.path.substring(article.path.lastIndexOf('/') + 1).replace(/-/g, ' '));
```
Comment (bstopp) [inline cigaradvisor/blocks/article-teaser/article-teaser.js:33]: This should actually be the article's title, not the URL value.

**Review by bstopp — CHANGES_REQUESTED** [review]

File: cigaradvisor/blocks/article-teaser/article-teaser.js (hunk 1 above)
Comment (kailasnadh790) [reply cigaradvisor/blocks/article-teaser/article-teaser.js]: changed to heading.

Comment (kailasnadh790) [reply cigaradvisor/blocks/article-teaser/article-teaser.js]: felt heading is more readable than title

**Review by bstopp — APPROVED** [review]
