### PR TITLE
Bug/249

### LINKED ISSUE #249: All Index fetching needs to handle default fetch limit of 1000
When doing full text search, or listing all articles, the index by default only returns 1000 per request.

The retrieval logic needs to make subsequent fetches to get all the data.

### LINKED ISSUE #252: Article List Lookup by Category should use individual Category index

### PR DESCRIPTION
**Pull request by kailasnadh790**
Fix #249 
Fix #252 

Test URLs:
- Before: https://main--famous-smoke-cigaradvisor--hlxsites.hlx.page/cigaradvisor
- After:  https://bug-249--famous-smoke-cigaradvisor--hlxsites.hlx.page/cigaradvisor

### CODE REVIEW

File: cigaradvisor/scripts/scripts.js [hunk 1]
```diff
@@ -248,21 +248,27 @@ export function getRelativePath(path) {
...
+const articleIndexData = [];
 /**
  * Returns all the posts in the posts index.
  *
  * @return {Promise<Array[Object]>}
  */
-export async function loadPosts() {
-  if (!articleIndexData) {
-    const resp = await fetch(ARTICLE_INDEX_PATH);
+export async function loadPosts(path = ARTICLE_INDEX_PATH, flag = false) {
```
Comment (bstopp) [inline cigaradvisor/scripts/scripts.js:257]: What does `flag` mean?

File: cigaradvisor/blocks/article-list/article-list.js [hunk 2]
```diff
@@ -29,10 +29,10 @@ export async function renderPage(wrapper, articles, limit) {
     const articleTeaser = document.createElement('div');
     articleTeaser.classList.add('article-teaser');
     articleTeaser.classList.add('block');
-    if (typeof article.author === 'string') {
-      article.author = await fetchAuthorInfo(article.author);
+    if (article.author) {
+      article.author = typeof article.author === 'string' ? await fetchAuthorInfo(article.author) : '';
     }
```
Comment (bstopp) [inline cigaradvisor/blocks/article-list/article-list.js:34]: This will break the author - if it is already populated with an object, then it replaces that object with an empty string.

File: cigaradvisor/blocks/article-list/article-list.js [hunk 3]
```diff
@@ -29,10 +29,10 @@ export async function renderPage(wrapper, articles, limit) {
...
-    if (typeof article.category === 'string') {
+    if (article.category && typeof article.category === 'string') {
```
Comment (bstopp) [inline cigaradvisor/blocks/article-list/article-list.js:35]: I'm not sure this is necessary.

`typeof article.category === 'string'` is _false_, when it is undefined, or an object - why introduce a change?

File: cigaradvisor/scripts/scripts.js [hunk 4]
```diff
@@ -248,21 +248,27 @@ export function getRelativePath(path) {
...
     let jsonData = '';
     if (resp.ok) {
       jsonData = await resp.json();
     }
-    articleIndexData = jsonData.data;
+    jsonData.data.forEach((a) => {
+      articleIndexData.push({ ...a });
+    });
+    // If there are more articles to load, load them
+    if ((jsonData.total - jsonData.offset) > jsonData.limit) {
```
Comment (bstopp) [inline cigaradvisor/scripts/scripts.js:268]: We shouldn't load _all of the posts_, unless the caller actually wants _all of the posts_. So we need to probably reassess how this entire post logic works.

File: cigaradvisor/blocks/search-results/search-results.js [hunk 5]
```diff
@@ -59,14 +59,10 @@ async function handleSearch(searchValue, wrapper, limit) {
   const filteredData = filterData(searchTerms, data);
 
   const articles = [];
-  const promises = [];
+  const allArticles = await loadPosts();
   filteredData.forEach((post) => {
-    promises.push(fetchPostsInfo(post.path));
```
Comment (bstopp) [inline cigaradvisor/blocks/search-results/search-results.js:64]: I'm not sure that this should be removed, i am wondering if all of the different locations in which this article list is found have been tested thoroughly.

**Review by bstopp — CHANGES_REQUESTED** [review]

File: cigaradvisor/scripts/scripts.js (hunk 1 above)
Comment (kailasnadh790) [reply cigaradvisor/scripts/scripts.js:257]: flag is set to true for subsequent calls when there are more articles than the limit.

File: cigaradvisor/scripts/scripts.js (hunk 4 above)
Comment (kailasnadh790) [reply cigaradvisor/scripts/scripts.js:268]: hmm...I am trying to think about a case where we don't have to get all the posts.

File: cigaradvisor/blocks/search-results/search-results.js (hunk 5 above)
Comment (kailasnadh790) [reply cigaradvisor/blocks/search-results/search-results.js:64]: yes

File: cigaradvisor/blocks/article-list/article-list.js (hunk 2 above)
Comment (kailasnadh790) [reply cigaradvisor/blocks/article-list/article-list.js:34]: for some article article.author was null.

File: cigaradvisor/scripts/scripts.js (hunk 1 above)
Comment (bstopp) [reply cigaradvisor/scripts/scripts.js:257]: the name of the parameter should reflect it's intent/use. 'flag' doesn't convey any context.

File: cigaradvisor/scripts/scripts.js (hunk 4 above)
Comment (bstopp) [reply cigaradvisor/scripts/scripts.js:268]: If we're going to load all of the posts, is there a reason we need to recurse into this method, rather than just loop?

**Review by bstopp — CHANGES_REQUESTED** [review]

**Review by tmaret — APPROVED** [review]
